# Generated by Django 4.2.23 on 2025-10-03 12:14

from django.db import migrations, models
import geonode_mapstore_client.models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_mapstore_client", "0004_auto_20231114_1705"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extension",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the extension, derived from the zip file name. Must be unique.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        help_text="Upload the MapStore extension as a zip folder.",
                        upload_to=geonode_mapstore_client.models.extension_upload_path,
                        validators=[geonode_mapstore_client.models.validate_zip_file],
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the extension is active and should be included in the index.",
                    ),
                ),
                (
                    "is_map_extension",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this extension is a map-specific plugin for Map Viewers.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MapStore Extension",
                "verbose_name_plural": "MapStore Extensions",
                "ordering": ("name",),
            },
        ),
    ]
