# Generated by Django 3.2.22 on 2023-11-13 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geonode_mapstore_client", "0005_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name='searchservice',
            name='name',
            field=models.CharField(
                max_length=250,
                null=False,
                verbose_name="Service Name",
                help_text="The name of Search Service",
                default="",
            ),
        ),
    ]
