# Generated by Django 5.2.7 on 2025-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_mapstore_client", "0006_searchservice_namefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchservice",
            name="sub_title",
            field=models.CharField(
                help_text="Sub title of the Search Service",
                max_length=250,
                null=True,
                verbose_name="Service SubTitle",
            ),
        ),
        migrations.AlterField(
            model_name="searchservice",
            name="display_name",
            field=models.CharField(
                help_text="Literal template to be returned as result, Ex. 'UNESCO - ${properties.site}'",
                max_length=250,
                verbose_name="Result string",
            ),
        ),
        migrations.AlterField(
            model_name="searchservice",
            name="name",
            field=models.CharField(
                default="",
                help_text="Name of the Search Service",
                max_length=250,
                verbose_name="Service Name",
            ),
        ),
    ]
